services:
  postgress:
    image: postgres:17.11
    container_name: postgres
    environment:
      POSGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  clickhouse:
    image: clickhouse/clickhouse-server:26.3
    container_name: clickhouse
    environment:
      CLICKHOUSE_USER: user
      CLICKHOUSE_PASSWORD: password
      CLICKHOUSE_DB: testdb
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse

volumes:
  pgdata:
  clickhouse_data:
